### PR TITLE
Remove duplicated if condition

### PR DESCRIPTION
**Pull request by christopherjwang**
I was using your codebase to make https://github.com/faustbrian/ARK-PHP/pull/2 and ran into this. Also, is there a misspelling in signiture (I think it should be signature)?

### CODE REVIEW

**Comment by dafty** [comment]
This is not a duplicate condition. This was added because `TransactionType.SECONDSIGNITURE` has now been deprecated, but is still a valid type until people change their code to use the new `TransactionType.SECONDSIGNATURE`. There would be a compilation warning if it was duplicated.

See https://github.com/ArkEcosystem/ark-java/pull/24 for when this was added.

Will revert these changes.

**Comment by christopherjwang** [comment]
that's my bad, I thought they were the exact same `type == something` condition

**Comment by boldninja** [comment]
@christopherjwang provide me with your ARK address or contact me on Ark slack (boldninja) if you don't want to share it publicly.

**Comment by christopherjwang** [comment]
verification: 09sad8(8

**Pull request merged**
