### PR TITLE
Accept query parameters when sending request to peer.

### PR DESCRIPTION
**Pull request by Maxinger**
Currently there is no way to pass URL parameters when sending request to a peer.
This call doesn't work
`peer.request("GET", "/api/blocks?offset=100&limit=50").get()`
because the question mark is escaped, which makes the path invalid: `/api/delegates%3Foffset=100&limit=50`

The new optional argument `query` makes such calls possible:
`peer.request("GET", "/api/blocks", "offset=100&limit=50").get()`

### CODE REVIEW

**Comment by fix** [comment]
sorry for being late, can you resubmit a PR merged with recent changes, i am not able to do it here quickly

**Comment by Maxinger** [comment]
I've updated the PR, please review.

**Comment by Guppster** [comment]
This may not be possible but passing query params as a 'raw' string seems to be a gross way of handling that. Can we change this to a map with key `queryKey` and value `queryValue`?

Also it would be awesome if you could write a test for this

**Comment by Guppster** [comment]
Take a look at #18 . Sorry i had to make a new PR because there were just too many merge commits (6) in your master branch.

**Pull request closed without merging**
