### PR TITLE
Version 1.0.0

### PR DESCRIPTION
**Pull request by Guppster**
This PR contains my purposed 1.0 release of the Ark-Java library. The code has been rewritten in Kotlin because I feel Kotlin improves the structure and safety of the library as well as increase exposure and allow more people to work on the development of the library. It will allow people to integrate this library into their Android applications easier and overall just cleans up the code and makes it more readable.

All previous fixes submitted to the legacy version have been ported over. Some recent issues include
#6, #5, #23, #27, #24, and #21 

The general enhancements in this version include:
- Larger test suite using mocks (#22)
- Automated testing with Travis (#25)
- Automated deployment to Bintray Repo (#25)
- Complete code documentation
- Improved README with clear instructions
- Isolated network operations
- Type checked data objects for responses received from the API (no more stray JSON)
- Dynamic peer list fetching

Currently, the Bintray repo associated with this is owned by me, I am happy to continue maintaining this but if the admins wish to use their repo you need to set the Travis environment variables and change the subject in ./descriptor.json

### CODE REVIEW

**Comment by Guppster** [comment]
@dafty @fix

**Comment by dafty** [comment]
Looks good to me on initial inspection. For now, will merge into 1.0.0 so I can make changes to the bintray repo and do some further testing with Travis on a separate branch.

Haven't got any time this weekend since I am out of the country, but changes should be finished and merged to master next week.

@boldninja

**Comment by Guppster** [comment]
Any update on this? Let me know if there are any issues, i'll be glad to help fix them

**Comment by dafty** [comment]
@Guppster Thanks for your help with this. Merged.

**Pull request merged**
