### PR TITLE
Implement Smarter Peer Choices, Load Peers from Network

### PR DESCRIPTION
**Pull request by okjintao**
Please review #34 first. This pull request is built on top of it and is currently showing its changes too. 

Refactor ArkNet classes to take more advantage of OOP, cut down on useless code
Dramatically cut down HttpUtils noise -> Rename to RequestManager
Begin transition to @dafty responses over model use.

### CODE REVIEW

**Comment by okjintao** [comment]
@dafty I'll rebase this and fix conflicts tonight. I'll probably also try to add some naive peer rotation given a timeout on currently selected peer.

**Comment by okjintao** [comment]
Additionally, I'll open a separate PR tonight finishing the v1 serialization of transactions (or at least a WIP) for the crypto v1. I feel it is important to finish this and start work on v2 ASAP.

**Comment by dafty** [comment]
Thanks, let me know if you want this kept open or create a new PR without the conflics.

V2 spec is not released yet, and will probably undergo at least a few weeks on devnet once released to test and give us a chance to update.

We will need to implement https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-11.md, but on the most part, there's no major changes.

**Comment by okjintao** [comment]
@dafty hey, sorry wasn't able to work on this one recently was busy. I should have time tonight to rebase and fix up these merge conflicts.

**Comment by okjintao** [comment]
here i fixed the conflict, go ahead and review this one i'll open a separate pr later for the serialization. i should have time tonight

**Comment by okjintao** [comment]
@dafty if this pr is alright can we merge it? i just finished the smart bridges for v1. i'll look at the AIP you sent me for v2.

**Comment by okjintao** [comment]
@dafty Closing in favor of #36 
please review this and merge as you can. let me know what you think next steps should be.

**Pull request closed without merging**
